/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MealPlan {
  'description_en' : string,
  'description_fr' : string,
  'recipe_ids' : Array<bigint>,
  'difficulty' : { 'easy' : null } |
    { 'hard' : null } |
    { 'medium' : null },
  'duration_days' : bigint,
  'diet_type' : { 'non_vegetarian' : null } |
    { 'vegetarian' : null },
  'name_en' : string,
  'name_fr' : string,
  'price' : bigint,
}
export interface Recipe {
  'prep_time_min' : bigint,
  'description_en' : string,
  'description_fr' : string,
  'image_url' : string,
  'difficulty' : { 'easy' : null } |
    { 'hard' : null } |
    { 'medium' : null },
  'diet_type' : { 'non_vegetarian' : null } |
    { 'vegetarian' : null },
  'name_en' : string,
  'name_fr' : string,
  'category' : { 'breakfast' : null } |
    { 'lunch' : null } |
    { 'snack' : null } |
    { 'dinner' : null },
  'steps_en' : Array<string>,
  'steps_fr' : Array<string>,
  'ingredients_en' : Array<string>,
  'ingredients_fr' : Array<string>,
  'nutrition' : {
    'fat' : bigint,
    'carbs' : bigint,
    'calories' : bigint,
    'protein' : bigint,
  },
}
export interface _SERVICE {
  'addMealPlan' : ActorMethod<[MealPlan], bigint>,
  'addRecipe' : ActorMethod<[Recipe], bigint>,
  'chatbot' : ActorMethod<[string], string>,
  'getAllMealPlans' : ActorMethod<[], Array<MealPlan>>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getMealPlan' : ActorMethod<[bigint], MealPlan>,
  'getMealPlanRecommendations' : ActorMethod<
    [{ 'non_vegetarian' : null } | { 'vegetarian' : null }],
    Array<MealPlan>
  >,
  'getRecipe' : ActorMethod<[bigint], Recipe>,
  'getRecipesByCategory' : ActorMethod<
    [
      { 'breakfast' : null } |
        { 'lunch' : null } |
        { 'snack' : null } |
        { 'dinner' : null },
    ],
    Array<Recipe>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];