/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MealPlan = IDL.Record({
  'description_en' : IDL.Text,
  'description_fr' : IDL.Text,
  'recipe_ids' : IDL.Vec(IDL.Nat),
  'difficulty' : IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'duration_days' : IDL.Nat,
  'diet_type' : IDL.Variant({
    'non_vegetarian' : IDL.Null,
    'vegetarian' : IDL.Null,
  }),
  'name_en' : IDL.Text,
  'name_fr' : IDL.Text,
  'price' : IDL.Nat,
});
export const Recipe = IDL.Record({
  'prep_time_min' : IDL.Nat,
  'description_en' : IDL.Text,
  'description_fr' : IDL.Text,
  'image_url' : IDL.Text,
  'difficulty' : IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'diet_type' : IDL.Variant({
    'non_vegetarian' : IDL.Null,
    'vegetarian' : IDL.Null,
  }),
  'name_en' : IDL.Text,
  'name_fr' : IDL.Text,
  'category' : IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'snack' : IDL.Null,
    'dinner' : IDL.Null,
  }),
  'steps_en' : IDL.Vec(IDL.Text),
  'steps_fr' : IDL.Vec(IDL.Text),
  'ingredients_en' : IDL.Vec(IDL.Text),
  'ingredients_fr' : IDL.Vec(IDL.Text),
  'nutrition' : IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'protein' : IDL.Nat,
  }),
});

export const idlService = IDL.Service({
  'addMealPlan' : IDL.Func([MealPlan], [IDL.Nat], []),
  'addRecipe' : IDL.Func([Recipe], [IDL.Nat], []),
  'chatbot' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAllMealPlans' : IDL.Func([], [IDL.Vec(MealPlan)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getMealPlan' : IDL.Func([IDL.Nat], [MealPlan], ['query']),
  'getMealPlanRecommendations' : IDL.Func(
      [IDL.Variant({ 'non_vegetarian' : IDL.Null, 'vegetarian' : IDL.Null })],
      [IDL.Vec(MealPlan)],
      [],
    ),
  'getRecipe' : IDL.Func([IDL.Nat], [Recipe], ['query']),
  'getRecipesByCategory' : IDL.Func(
      [
        IDL.Variant({
          'breakfast' : IDL.Null,
          'lunch' : IDL.Null,
          'snack' : IDL.Null,
          'dinner' : IDL.Null,
        }),
      ],
      [IDL.Vec(Recipe)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MealPlan = IDL.Record({
    'description_en' : IDL.Text,
    'description_fr' : IDL.Text,
    'recipe_ids' : IDL.Vec(IDL.Nat),
    'difficulty' : IDL.Variant({
      'easy' : IDL.Null,
      'hard' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'duration_days' : IDL.Nat,
    'diet_type' : IDL.Variant({
      'non_vegetarian' : IDL.Null,
      'vegetarian' : IDL.Null,
    }),
    'name_en' : IDL.Text,
    'name_fr' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Recipe = IDL.Record({
    'prep_time_min' : IDL.Nat,
    'description_en' : IDL.Text,
    'description_fr' : IDL.Text,
    'image_url' : IDL.Text,
    'difficulty' : IDL.Variant({
      'easy' : IDL.Null,
      'hard' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'diet_type' : IDL.Variant({
      'non_vegetarian' : IDL.Null,
      'vegetarian' : IDL.Null,
    }),
    'name_en' : IDL.Text,
    'name_fr' : IDL.Text,
    'category' : IDL.Variant({
      'breakfast' : IDL.Null,
      'lunch' : IDL.Null,
      'snack' : IDL.Null,
      'dinner' : IDL.Null,
    }),
    'steps_en' : IDL.Vec(IDL.Text),
    'steps_fr' : IDL.Vec(IDL.Text),
    'ingredients_en' : IDL.Vec(IDL.Text),
    'ingredients_fr' : IDL.Vec(IDL.Text),
    'nutrition' : IDL.Record({
      'fat' : IDL.Nat,
      'carbs' : IDL.Nat,
      'calories' : IDL.Nat,
      'protein' : IDL.Nat,
    }),
  });
  
  return IDL.Service({
    'addMealPlan' : IDL.Func([MealPlan], [IDL.Nat], []),
    'addRecipe' : IDL.Func([Recipe], [IDL.Nat], []),
    'chatbot' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAllMealPlans' : IDL.Func([], [IDL.Vec(MealPlan)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getMealPlan' : IDL.Func([IDL.Nat], [MealPlan], ['query']),
    'getMealPlanRecommendations' : IDL.Func(
        [IDL.Variant({ 'non_vegetarian' : IDL.Null, 'vegetarian' : IDL.Null })],
        [IDL.Vec(MealPlan)],
        [],
      ),
    'getRecipe' : IDL.Func([IDL.Nat], [Recipe], ['query']),
    'getRecipesByCategory' : IDL.Func(
        [
          IDL.Variant({
            'breakfast' : IDL.Null,
            'lunch' : IDL.Null,
            'snack' : IDL.Null,
            'dinner' : IDL.Null,
          }),
        ],
        [IDL.Vec(Recipe)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };