/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MealPlan {
    description_en: string;
    description_fr: string;
    recipe_ids: Array<bigint>;
    difficulty: Variant_easy_hard_medium;
    duration_days: bigint;
    diet_type: Variant_non_vegetarian_vegetarian;
    name_en: string;
    name_fr: string;
    price: bigint;
}
export interface Recipe {
    prep_time_min: bigint;
    description_en: string;
    description_fr: string;
    image_url: string;
    difficulty: Variant_easy_hard_medium;
    diet_type: Variant_non_vegetarian_vegetarian;
    name_en: string;
    name_fr: string;
    category: Variant_breakfast_lunch_snack_dinner;
    steps_en: Array<string>;
    steps_fr: Array<string>;
    ingredients_en: Array<string>;
    ingredients_fr: Array<string>;
    nutrition: {
        fat: bigint;
        carbs: bigint;
        calories: bigint;
        protein: bigint;
    };
}
export enum Variant_breakfast_lunch_snack_dinner {
    breakfast = "breakfast",
    lunch = "lunch",
    snack = "snack",
    dinner = "dinner"
}
export enum Variant_easy_hard_medium {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum Variant_non_vegetarian_vegetarian {
    non_vegetarian = "non_vegetarian",
    vegetarian = "vegetarian"
}
export interface backendInterface {
    addMealPlan(mealPlan: MealPlan): Promise<bigint>;
    addRecipe(recipe: Recipe): Promise<bigint>;
    chatbot(message: string): Promise<string>;
    getAllMealPlans(): Promise<Array<MealPlan>>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getMealPlan(id: bigint): Promise<MealPlan>;
    getMealPlanRecommendations(dietType: Variant_non_vegetarian_vegetarian): Promise<Array<MealPlan>>;
    getRecipe(id: bigint): Promise<Recipe>;
    getRecipesByCategory(category: Variant_breakfast_lunch_snack_dinner): Promise<Array<Recipe>>;
}
import type { MealPlan as _MealPlan, Recipe as _Recipe } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMealPlan(arg0: MealPlan): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMealPlan(to_candid_MealPlan_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMealPlan(to_candid_MealPlan_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRecipe(arg0: Recipe): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(to_candid_Recipe_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(to_candid_Recipe_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async chatbot(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.chatbot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chatbot(arg0);
            return result;
        }
    }
    async getAllMealPlans(): Promise<Array<MealPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMealPlans();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMealPlans();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealPlan(arg0: bigint): Promise<MealPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlan(arg0);
                return from_candid_MealPlan_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlan(arg0);
            return from_candid_MealPlan_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealPlanRecommendations(arg0: Variant_non_vegetarian_vegetarian): Promise<Array<MealPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealPlanRecommendations(to_candid_variant_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealPlanRecommendations(to_candid_variant_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipe(arg0: bigint): Promise<Recipe> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_Recipe_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_Recipe_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipesByCategory(arg0: Variant_breakfast_lunch_snack_dinner): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipesByCategory(to_candid_variant_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipesByCategory(to_candid_variant_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MealPlan_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MealPlan): MealPlan {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description_en: string;
    description_fr: string;
    recipe_ids: Array<bigint>;
    difficulty: {
        easy: null;
    } | {
        hard: null;
    } | {
        medium: null;
    };
    duration_days: bigint;
    diet_type: {
        non_vegetarian: null;
    } | {
        vegetarian: null;
    };
    name_en: string;
    name_fr: string;
    price: bigint;
}): {
    description_en: string;
    description_fr: string;
    recipe_ids: Array<bigint>;
    difficulty: Variant_easy_hard_medium;
    duration_days: bigint;
    diet_type: Variant_non_vegetarian_vegetarian;
    name_en: string;
    name_fr: string;
    price: bigint;
} {
    return {
        description_en: value.description_en,
        description_fr: value.description_fr,
        recipe_ids: value.recipe_ids,
        difficulty: from_candid_variant_n11(_uploadFile, _downloadFile, value.difficulty),
        duration_days: value.duration_days,
        diet_type: from_candid_variant_n12(_uploadFile, _downloadFile, value.diet_type),
        name_en: value.name_en,
        name_fr: value.name_fr,
        price: value.price
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prep_time_min: bigint;
    description_en: string;
    description_fr: string;
    image_url: string;
    difficulty: {
        easy: null;
    } | {
        hard: null;
    } | {
        medium: null;
    };
    diet_type: {
        non_vegetarian: null;
    } | {
        vegetarian: null;
    };
    name_en: string;
    name_fr: string;
    category: {
        breakfast: null;
    } | {
        lunch: null;
    } | {
        snack: null;
    } | {
        dinner: null;
    };
    steps_en: Array<string>;
    steps_fr: Array<string>;
    ingredients_en: Array<string>;
    ingredients_fr: Array<string>;
    nutrition: {
        fat: bigint;
        carbs: bigint;
        calories: bigint;
        protein: bigint;
    };
}): {
    prep_time_min: bigint;
    description_en: string;
    description_fr: string;
    image_url: string;
    difficulty: Variant_easy_hard_medium;
    diet_type: Variant_non_vegetarian_vegetarian;
    name_en: string;
    name_fr: string;
    category: Variant_breakfast_lunch_snack_dinner;
    steps_en: Array<string>;
    steps_fr: Array<string>;
    ingredients_en: Array<string>;
    ingredients_fr: Array<string>;
    nutrition: {
        fat: bigint;
        carbs: bigint;
        calories: bigint;
        protein: bigint;
    };
} {
    return {
        prep_time_min: value.prep_time_min,
        description_en: value.description_en,
        description_fr: value.description_fr,
        image_url: value.image_url,
        difficulty: from_candid_variant_n11(_uploadFile, _downloadFile, value.difficulty),
        diet_type: from_candid_variant_n12(_uploadFile, _downloadFile, value.diet_type),
        name_en: value.name_en,
        name_fr: value.name_fr,
        category: from_candid_variant_n16(_uploadFile, _downloadFile, value.category),
        steps_en: value.steps_en,
        steps_fr: value.steps_fr,
        ingredients_en: value.ingredients_en,
        ingredients_fr: value.ingredients_fr,
        nutrition: value.nutrition
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Variant_easy_hard_medium {
    return "easy" in value ? Variant_easy_hard_medium.easy : "hard" in value ? Variant_easy_hard_medium.hard : "medium" in value ? Variant_easy_hard_medium.medium : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    non_vegetarian: null;
} | {
    vegetarian: null;
}): Variant_non_vegetarian_vegetarian {
    return "non_vegetarian" in value ? Variant_non_vegetarian_vegetarian.non_vegetarian : "vegetarian" in value ? Variant_non_vegetarian_vegetarian.vegetarian : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
}): Variant_breakfast_lunch_snack_dinner {
    return "breakfast" in value ? Variant_breakfast_lunch_snack_dinner.breakfast : "lunch" in value ? Variant_breakfast_lunch_snack_dinner.lunch : "snack" in value ? Variant_breakfast_lunch_snack_dinner.snack : "dinner" in value ? Variant_breakfast_lunch_snack_dinner.dinner : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MealPlan>): Array<MealPlan> {
    return value.map((x)=>from_candid_MealPlan_n9(_uploadFile, _downloadFile, x));
}
function to_candid_MealPlan_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MealPlan): _MealPlan {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Recipe_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recipe): _Recipe {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description_en: string;
    description_fr: string;
    recipe_ids: Array<bigint>;
    difficulty: Variant_easy_hard_medium;
    duration_days: bigint;
    diet_type: Variant_non_vegetarian_vegetarian;
    name_en: string;
    name_fr: string;
    price: bigint;
}): {
    description_en: string;
    description_fr: string;
    recipe_ids: Array<bigint>;
    difficulty: {
        easy: null;
    } | {
        hard: null;
    } | {
        medium: null;
    };
    duration_days: bigint;
    diet_type: {
        non_vegetarian: null;
    } | {
        vegetarian: null;
    };
    name_en: string;
    name_fr: string;
    price: bigint;
} {
    return {
        description_en: value.description_en,
        description_fr: value.description_fr,
        recipe_ids: value.recipe_ids,
        difficulty: to_candid_variant_n3(_uploadFile, _downloadFile, value.difficulty),
        duration_days: value.duration_days,
        diet_type: to_candid_variant_n4(_uploadFile, _downloadFile, value.diet_type),
        name_en: value.name_en,
        name_fr: value.name_fr,
        price: value.price
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prep_time_min: bigint;
    description_en: string;
    description_fr: string;
    image_url: string;
    difficulty: Variant_easy_hard_medium;
    diet_type: Variant_non_vegetarian_vegetarian;
    name_en: string;
    name_fr: string;
    category: Variant_breakfast_lunch_snack_dinner;
    steps_en: Array<string>;
    steps_fr: Array<string>;
    ingredients_en: Array<string>;
    ingredients_fr: Array<string>;
    nutrition: {
        fat: bigint;
        carbs: bigint;
        calories: bigint;
        protein: bigint;
    };
}): {
    prep_time_min: bigint;
    description_en: string;
    description_fr: string;
    image_url: string;
    difficulty: {
        easy: null;
    } | {
        hard: null;
    } | {
        medium: null;
    };
    diet_type: {
        non_vegetarian: null;
    } | {
        vegetarian: null;
    };
    name_en: string;
    name_fr: string;
    category: {
        breakfast: null;
    } | {
        lunch: null;
    } | {
        snack: null;
    } | {
        dinner: null;
    };
    steps_en: Array<string>;
    steps_fr: Array<string>;
    ingredients_en: Array<string>;
    ingredients_fr: Array<string>;
    nutrition: {
        fat: bigint;
        carbs: bigint;
        calories: bigint;
        protein: bigint;
    };
} {
    return {
        prep_time_min: value.prep_time_min,
        description_en: value.description_en,
        description_fr: value.description_fr,
        image_url: value.image_url,
        difficulty: to_candid_variant_n3(_uploadFile, _downloadFile, value.difficulty),
        diet_type: to_candid_variant_n4(_uploadFile, _downloadFile, value.diet_type),
        name_en: value.name_en,
        name_fr: value.name_fr,
        category: to_candid_variant_n7(_uploadFile, _downloadFile, value.category),
        steps_en: value.steps_en,
        steps_fr: value.steps_fr,
        ingredients_en: value.ingredients_en,
        ingredients_fr: value.ingredients_fr,
        nutrition: value.nutrition
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_easy_hard_medium): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Variant_easy_hard_medium.easy ? {
        easy: null
    } : value == Variant_easy_hard_medium.hard ? {
        hard: null
    } : value == Variant_easy_hard_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_non_vegetarian_vegetarian): {
    non_vegetarian: null;
} | {
    vegetarian: null;
} {
    return value == Variant_non_vegetarian_vegetarian.non_vegetarian ? {
        non_vegetarian: null
    } : value == Variant_non_vegetarian_vegetarian.vegetarian ? {
        vegetarian: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_breakfast_lunch_snack_dinner): {
    breakfast: null;
} | {
    lunch: null;
} | {
    snack: null;
} | {
    dinner: null;
} {
    return value == Variant_breakfast_lunch_snack_dinner.breakfast ? {
        breakfast: null
    } : value == Variant_breakfast_lunch_snack_dinner.lunch ? {
        lunch: null
    } : value == Variant_breakfast_lunch_snack_dinner.snack ? {
        snack: null
    } : value == Variant_breakfast_lunch_snack_dinner.dinner ? {
        dinner: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
